command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID" 
    value: "<WAREHOUSE_ID>"
  - name: "DATABRICKS_WAREHOUSE_HTTP_PATH"
    value: "/sql/1.0/warehouses/<WAREHOUSE_ID>"
  - name: DATABRICKS_HOST
    value: "https://e2-demo-field-eng.cloud.databricks.com"

# Service principal authentication - user authorization scopes removed for production
